config/routes.rb
Rails.application.routes.draw do

  resources :categories

  resources :recipes

  resources :users

  get "/admin", controller: 'admin',action: 'index'

  get "/contact", controller: 'home',action: 'contact', as: 'contact'

  get "/about", controller: 'home',action: 'about', as: 'about'

  root controller: 'home', action: 'index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :ingredients, presence: true
  validates :instructions, presence: true

  def self.find_all_by_query(query)
    query = query.downcase
    query = "%#{query}%"

    category_id = "%#{category_id}% > option"



    Recipe.where(['lower(title) like ?
                  OR lower(ingredients) like ?
                  OR lower(instructions) like ?
                  OR category_id like ?',
                  query, query, query, category_id])


  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  def recipes
    @recipes ||= find_recipes
  end

  def find_recipes
    Recipe.find(:all, :conditions => conditions)
  end

  def keyword_conditions
    ["recipes.title LIKE ?", "%#{keywords}%"] unless keywords.blank?
  end

  def category_conditions
    ["recipes.category_id = ?", category_id] unless category_id.blank?
  end

  def conditions
    [conditions_clauses.join(' AND '), *conditions_options]
  end

  def conditions_clauses
    conditions_parts.map { |condition| condition.first }
  end

  def conditions_options
    conditions_parts.map {|condition| condition[1..-1]}.flatten
  end

  def conditions_parts
    private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password

  def self.authenticate(username, password)
    user = User.where(username: username).first
    user && user.authenticate(password)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate

  def index
  
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?
  helper_method :current_user
  private
    def authenticate

      if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
        session[:user_id] = user.id
        session[:logged_in] = true

      else
          request_http_basic_authentication
      end
    end

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end






      def logged_in?
        session[:logged_in]
      end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show]

  # GET /recipes
  # GET /recipes.json
  def index
    @categories = Category.all

  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipes = @category.recipes
  end

  def set_category
    #abort(params.inspect)
    @category = Category.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  def get_recipes
    @recipes = Recipe.all.collect{|r| [r.category_id] }
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @number_of_recipes = Recipe.count
    @title = "Cookbook"
  end

  def about
    @title = "About"
  end

  def contact
    @title = "Contact"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate, :except =>[:index, :show]
  before_action :get_categories, :only =>[:new, :edit, :create, :update]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:q]
      @recipes = Recipe.find_all_by_query(params[:q])
    else
      @recipes = Recipe.all
    end
    @title = "Recipe List"
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @title = @recipe.title
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @title = "New Recipe"
  end

  # GET /recipes/1/edit
  def edit
    @title = "Edit Recipe"
  end

  # POST /recipes
  # POST /recipes.json
  def create

    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.includes(:category).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :instructions, :category_id, :calories)
    end

    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id] }
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/admin/index.html.erb
<p>You are currently logged in as <%= current_user.username %>
</p>

app/views/categories/index.html.erb
<h1>Category List</h1>

<table>
  <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>

      </tr>
    <% end %>
</table>

app/views/categories/show.html.erb
<h1><%= @category.name %> </h1>

<table>
  <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.title, recipe %></td>

      </tr>
    <% end %>
</table>

app/views/home/about.html.erb
<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

app/views/home/contact.html.erb
<h2>Contact Us</h2>
<p>Contact Info...</p>

app/views/home/index.html.erb
<%= render "/shared/search" %>
<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="container">
      <header>
        <h1>Our Cookbook</h1>
      </header>

      <nav>
        <%=link_to_unless_current 'Home', root_url %>
        <%=link_to_unless_current 'Recipes', recipes_url %>
        <%=link_to_unless_current 'Categories', categories_url %>
        <%=link_to_unless_current 'About', about_url %>
        <%=link_to_unless_current 'Contact', contact_url %>
      </nav>

      <% if notice %>
      <div id="notice">
        <%= notice %>
      </div>
      <% end %>

      <section class="content">
        <%= yield %>
      </section>
      <footer>
        <h4>Copyright&copy; <%=Date.today.year %> OurCookbook</h4>
      </footer>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title">
    <%= f.label :title %><sup>*</sup><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><sup>*</sup><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :instructions %><sup>*</sup><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :calories %><sup>*</sup><br>
    <%= f.text_area :calories %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="required">
    <p><sup>*</sup>Required</p>
  </div>

<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>
<h1>Listing Recipes</h1>

<table>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Calories</th>
      <th>Last Updated</th>
      <th colspan="3"></th>
    </tr>

    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.title, recipe %></td>
        <td><%= recipe.category.name rescue "No Category" %></td>
        <td><%= recipe.calories %></td>
        <td><%= time_ago_in_words(recipe.updated_at) %></td>

          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>

          <td><%= button_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
      <% end %>
</table>


  <%= link_to 'New Recipe', new_recipe_path %>

<% if @logged_in %>
You are currently logged in as <%= current_user.username %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<article>
  <header>

    <h2>
      <%= @recipe.title %>
     [ <%= link_to 'Edit', edit_recipe_path(@recipe) %> ]
    </h2>

  </header>

  <h3>Ingredients:</h3>
  <p><%= @recipe.ingredients %></p>

  <h3>Intructions</h3>
  <p><%= @recipe.instructions %></p>

  <h3>Calories</h3>
  <p><%= @recipe.calories %></p>

</article>
<br />

<p>Category: <%= h(@recipe.category.name) rescue 'No category found' %></p>
<p><%= link_to 'Back', recipes_path %></p>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>
  <label for="query">Keywords: </label>
  <input type="search" id="query" name="q" value="<%= params[:q] %>">

  <%=select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name"), :include_blank => true  %>

  <input type="submit" value="Search">
<% end %>